### ISSUE TITLE
Duplicated area choices in Russian

### ISSUE THREAD

**Issue by georgy-komarov** [mirumee/google-i18n-address#40]
I found some nasty bug in Saleor ([here](https://github.com/mirumee/saleor/issues/3764)) when **Russian** (RU) area choices were duplicated. After some debugging that led me to this part of code.
https://github.com/mirumee/google-i18n-address/blob/1b87d1f7c014aa065f10ae565faa82c8d0e9390a/i18naddress/__init__.py#L100-L119
As we can see variants are added to `choices` list both in lines 108 and 117.
I think this bug should be somehow fixed (but I don't really know how)

**Comment by patrys** [comment]
Are the same names repeated? If the spelling is different then it's expected behavior as some country areas have multiple valid names.

**Comment by georgy-komarov** [comment]
<img src="https://user-images.githubusercontent.com/13136992/53350255-c9005880-392f-11e9-9352-c2a03ecfd7d6.png" width="300"></img>
If you look at the screenshot you can see that both russian name and transliterated ones are added to `choices` list. 
This leads to something like this in Saleor:
<img src="https://user-images.githubusercontent.com/13136992/53255369-8a239600-36d6-11e9-84a6-24a10b96a321.png" width="300"></img>

Moreover this problem also appears in Ukraine (UA), Armenia (AM), Hong Kong (HK), China (CN), Egypt (EG) and may be in some other countries that use non-Latin alphabet.

**Comment by patrys** [comment]
I would say the API behaves correctly here, it's the UI that is somewhat surprising. I'm not sure why they are rendered this way.

**Comment by georgy-komarov** [comment]
Honesly, I am not quite sure if it is Saleor UI rendering problem. 

As I understood, when saleor initializes, it makes up all country forms with a [for loop](https://github.com/mirumee/saleor/blob/1212b721bf17a1a1d2126ce81f1225960cb40b42/saleor/account/i18n.py#L275-L277) and `i18naddress.getvalidationrules` function.
At this point we already have more `country_area_choices` than we should. For example, in Russia there are 85 regions _(region = federal subject = oblast)_. But there are 170 _(2 times more)_ values in `country_area_choices` list.
And after that the list is [used in `account.i18n.update_base_fields`](https://github.com/mirumee/saleor/blob/1212b721bf17a1a1d2126ce81f1225960cb40b42/saleor/account/i18n.py#L227-L229) ([called from](https://github.com/mirumee/saleor/blob/1212b721bf17a1a1d2126ce81f1225960cb40b42/saleor/account/i18n.py#L256) `account.i18n.construct_address_form`), where it is put to `CountryAreaChoiceField` and becomes field of country form.

If I am correct it is either API problem or Chromium's repository mistake (?) or some filter is needed in Saleor to delete duplicated values.

**Comment by patrys** [comment]
The thing is the values are not duplicated, it provides all valid spellings for all regions, there are countries with two or three official languages where regions have different names based on the language of the speaker. This library provides validation data so it needs to recognize all possible names of each region, otherwise, an application would discard perfectly valid region names like transliterated latin oblast names in Russia.

PS: Keep in mind that not everyone can read (or more importantly, write in) Cyrillic so it may not be possible for someone to enter a name in Russian (or Chinese, or Korean, there are people who don't know the Latin alphabet). People may also have other spellings saved in their browser (including addresses returned by APIs such as the Payment Request), which is why the region field is not a select box.

**Comment by mociepka** [comment]
I think we should consider some configuration for this language case. It is confusing for many developers. We are try to cover all cases here but if that is no point for a dev we should give ability to use a "common" solution.
